name: paper-hypercube-projection

channels:
  - conda-forge

dependencies:
  - python=3.13.3

  - networkx=3.4.2
  - numpy=2.2.6
  - scipy=1.15.2

  - colorcet=3.1.0
  - matplotlib=3.10.3

  - jupyterlab
